#!/usr/bin/env python3
"""Switch active feature by concatenating shared + feature CLAUDE.md into root CLAUDE.md.

Usage:
  python scripts/switch_feature.py              # list features + show current active
  python scripts/switch_feature.py <name>       # switch to feature <name>
  python scripts/switch_feature.py -h           # show this help
"""
import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FEATURES_DIR = ROOT / "features"
SHARED_MD = FEATURES_DIR / "_shared" / "CLAUDE.md"
ROOT_CLAUDE = ROOT / "CLAUDE.md"

ACTIVE_MARKER = re.compile(r"<!--\s*ACTIVE_FEATURE:\s*(\S+)\s*-->")


def list_features() -> list[str]:
    """Feature directories under features/ (skips names starting with _)."""
    if not FEATURES_DIR.is_dir():
        return []
    return sorted(
        d.name
        for d in FEATURES_DIR.iterdir()
        if d.is_dir() and not d.name.startswith("_") and (d / "CLAUDE.md").is_file()
    )


def current_active() -> str | None:
    """Read ACTIVE_FEATURE marker from root CLAUDE.md."""
    if not ROOT_CLAUDE.is_file():
        return None
    m = ACTIVE_MARKER.search(ROOT_CLAUDE.read_text(encoding="utf-8"))
    return m.group(1) if m else None


def switch_to(name: str) -> int:
    feature_md = FEATURES_DIR / name / "CLAUDE.md"
    if not feature_md.is_file():
        print(f"[error] features/{name}/CLAUDE.md not found", file=sys.stderr)
        avail = ", ".join(list_features()) or "(none)"
        print(f"[info]  available: {avail}", file=sys.stderr)
        return 1
    if not SHARED_MD.is_file():
        print(f"[error] features/_shared/CLAUDE.md not found", file=sys.stderr)
        return 1

    header = (
        f"<!-- ACTIVE_FEATURE: {name} -->\n"
        f"<!-- Generated by scripts/switch_feature.py at "
        f"{datetime.now().isoformat(timespec='seconds')}. "
        f"Do not edit directly — edit features/_shared/CLAUDE.md or "
        f"features/{name}/CLAUDE.md and re-run. -->\n\n"
    )
    shared = SHARED_MD.read_text(encoding="utf-8").rstrip() + "\n"
    feature = feature_md.read_text(encoding="utf-8").rstrip() + "\n"
    ROOT_CLAUDE.write_text(header + shared + "\n---\n\n" + feature, encoding="utf-8")

    print(f"[ok] switched to: {name}")
    print(f"     CLAUDE.md <- features/_shared/CLAUDE.md + features/{name}/CLAUDE.md")
    return 0


def print_list() -> int:
    features = list_features()
    active = current_active()
    if not features:
        print("(no features found under features/)")
        return 0
    print("Features:")
    for f in features:
        prefix = "  * " if f == active else "    "
        print(f"{prefix}{f}")
    if active is None:
        print("\n[note] no ACTIVE_FEATURE marker in root CLAUDE.md — run with <name> to activate")
    elif active not in features:
        print(f"\n[warn] active='{active}' has no matching features/{active}/ directory")
    return 0


def main() -> int:
    argv = sys.argv[1:]
    if not argv or argv[0] in ("--list", "-l", "list"):
        return print_list()
    if argv[0] in ("-h", "--help"):
        print(__doc__)
        return 0
    if argv[0].startswith("-"):
        print(f"[error] unknown flag: {argv[0]}", file=sys.stderr)
        return 2
    return switch_to(argv[0])


if __name__ == "__main__":
    sys.exit(main())
